seed: 42
model_type: "random_forest"

collect_data:
    endtime: "2022-09-01"
    maxlatitude: 55.588 
    minlatitude: 40.459
    maxlongitude: 87.012
    minlongitude: 46.055
    minmagnitude: 0

target:
    mag_max_target_th: 5

preprocess:
    na_strategy: "zero" # zero, min, max
    roll_years_agg: [3, 10, 25, 50, 80, 100]

train_test_split:
    test_size: 0.2
    dropzero_train: true # false, true
    dropzero_test: false # true, false
    
random_forest:
    params:
        n_estimators: 500
        max_depth: 10
lightgbm:
    params:
        n_estimators: 500
        max_depth: -1